
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUM PLUS RPAREN TIMES VARexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMfactor : VARfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUM':([0,6,7,8,9,10,],[4,4,4,4,4,4,]),'VAR':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'LPAREN':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,5,12,13,14,15,16,],[0,-3,-6,-7,-8,-1,-2,-4,-5,-9,]),'PLUS':([1,2,3,4,5,11,12,13,14,15,16,],[7,-3,-6,-7,-8,7,-1,-2,-4,-5,-9,]),'MINUS':([1,2,3,4,5,11,12,13,14,15,16,],[8,-3,-6,-7,-8,8,-1,-2,-4,-5,-9,]),'RPAREN':([2,3,4,5,11,12,13,14,15,16,],[-3,-6,-7,-8,16,-1,-2,-4,-5,-9,]),'TIMES':([2,3,4,5,12,13,14,15,16,],[9,-6,-7,-8,9,9,-4,-5,-9,]),'DIVIDE':([2,3,4,5,12,13,14,15,16,],[10,-6,-7,-8,10,10,-4,-5,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,],[1,11,]),'term':([0,6,7,8,],[2,2,12,13,]),'factor':([0,6,7,8,9,10,],[3,3,3,3,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser_LR_PLY.py',34),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser_LR_PLY.py',38),
  ('expression -> term','expression',1,'p_expression_term','parser_LR_PLY.py',42),
  ('term -> term TIMES factor','term',3,'p_term_times','parser_LR_PLY.py',46),
  ('term -> term DIVIDE factor','term',3,'p_term_divide','parser_LR_PLY.py',50),
  ('term -> factor','term',1,'p_term_factor','parser_LR_PLY.py',54),
  ('factor -> NUM','factor',1,'p_factor_num','parser_LR_PLY.py',58),
  ('factor -> VAR','factor',1,'p_factor_var','parser_LR_PLY.py',62),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_group','parser_LR_PLY.py',66),
]
